Bump arduino/setup-task from 2 to 3 (#93)
Bumps [arduino/setup-task](https://github.com/arduino/setup-task) from 2
to 3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/arduino/setup-task/releases">arduino/setup-task's
releases</a>.</em></p>
<blockquote>
<h2>3.0.0</h2>
<h2>Migration Guide</h2>
<p>The version of the <a
href="https://nodejs.org/en/about"><strong>Node.js</strong></a> runtime
used to execute the action has been updated from 20 to 24. This could be
a breaking change for certain GitHub Actions workflows.</p>
<p>If a workflow with dependency on the
<strong>arduino/setup-task</strong> action uses only <a
href="https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners">GitHub-hosted
GitHub Actions runners</a>, no changes are required.</p>
<p>If the workflow uses a <a
href="https://docs.github.com/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners">self-hosted
runner</a>, the workflow run might fail after updating
<strong>arduino/setup-task</strong>:</p>
<pre lang="text"><code>Error: System.ArgumentOutOfRangeException:
Specified argument was out of the range of valid values. (Parameter
''using: node24' is not supported, use 'docker', 'node16' or 'node20'
instead.')
at
GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext
executionContext, TemplateContext templateContext, TemplateToken
inputsToken, String fileRelativePath, MappingToken outputs)
at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext
executionContext, String manifestFile)
Error: Fail to load arduino/setup-task/v3/action.yml
</code></pre>
<p>This means an older runner version that does not provide Node.js 24.x
is installed on the runner machine. In this case, the runner must be
updated to a modern version with Node.js 24.x support prior to updating
the <strong>arduino/setup-task</strong> action in the affected
workflow.</p>
<h2>Changelog</h2>
<h3>Breaking</h3>
<ul>
<li>Update Node.js runtime for action from 20 to 24 (<a
href="https://redirect.github.com/arduino/setup-task/issues/1408">#1408</a>)</li>
</ul>
<h3>Enhancement</h3>
<ul>
<li>Convert project to ECMAScript module format (<a
href="https://redirect.github.com/arduino/setup-task/issues/1410">#1410</a>)</li>
<li><a
href="https://github.com/arduino/setup-task/pulls?q=merged%3A2024-02-07..2026-06-30+author%3Aapp%2Fdependabot">Various
dependency updates</a></li>
</ul>
<h2>Full Changeset</h2>
<p><a
href="https://github.com/arduino/setup-task/compare/2.0.0...3.0.0">https://github.com/arduino/setup-task/compare/2.0.0...3.0.0</a></p>
<h2>Contributors</h2>
<ul>
<li><a href="https://github.com/tbjers"><code>@​tbjers</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/arduino/setup-task/commit/c0bc642852239c2689f73f4ea6459c29405f3c52"><code>c0bc642</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1412">#1412</a>
from arduino/dependabot/npm_and_yarn/prettier-3.9.4</li>
<li><a
href="https://github.com/arduino/setup-task/commit/c07d23ea793b3a5079f5da132345e36183e80c16"><code>c07d23e</code></a>
build(deps-dev): bump prettier from 3.9.3 to 3.9.4</li>
<li><a
href="https://github.com/arduino/setup-task/commit/f08c616dcb5ae62ea47eee8cc9911c59ce13cd90"><code>f08c616</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1413">#1413</a>
from arduino/dependabot/npm_and_yarn/vercel/ncc-0.44.1</li>
<li><a
href="https://github.com/arduino/setup-task/commit/92587414bbffd5f297a4d1f30510c4f447228aa3"><code>9258741</code></a>
build(deps-dev): bump <code>@​vercel/ncc</code> from 0.44.0 to
0.44.1</li>
<li><a
href="https://github.com/arduino/setup-task/commit/5da2ac77a85b357a4d3e163ae651fd180f365535"><code>5da2ac7</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1341">#1341</a>
from arduino/dependabot/npm_and_yarn/actions/tool-ca...</li>
<li><a
href="https://github.com/arduino/setup-task/commit/939b4bbabffe5d1effc3740af4eb8be032d74341"><code>939b4bb</code></a>
Update dependency license metadata cache for
<code>@actions/tool-cache</code> bump</li>
<li><a
href="https://github.com/arduino/setup-task/commit/8ee93edf455c7aece15318ba3664b851d61fc9ee"><code>8ee93ed</code></a>
Repackage action following <code>@actions/tool-cache</code> bump</li>
<li><a
href="https://github.com/arduino/setup-task/commit/d179139bcb35cbf33f7538a4e9e8ad47f4a2ece0"><code>d179139</code></a>
build(deps): bump <code>@​actions/tool-cache</code> from 3.0.1 to
4.0.0</li>
<li><a
href="https://github.com/arduino/setup-task/commit/fdf1a08b64f84aa451e0513053f5fa8977075e2e"><code>fdf1a08</code></a>
Merge pull request <a
href="https://redirect.github.com/arduino/setup-task/issues/1340">#1340</a>
from arduino/dependabot/npm_and_yarn/actions/io-3.0.2</li>
<li><a
href="https://github.com/arduino/setup-task/commit/b3c627a805d5433989ce4dee31a6af95f5275055"><code>b3c627a</code></a>
Repackage action following <code>@actions/io</code> bump</li>
<li>Additional commits viewable in <a
href="https://github.com/arduino/setup-task/compare/v2...v3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=arduino/setup-task&package-manager=github_actions&previous-version=2&new-version=3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>